# Generated by Django 5.1.5 on 2025-01-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0002_remove_rutina_bloques_bloque_rutina_bloques'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='duracion',
            field=models.PositiveIntegerField(default=10, help_text='Duración del bloque en minutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque',
            name='rutina',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_de_rutina', to='ChillFit.rutina'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='bloques',
        ),
        migrations.AddField(
            model_name='rutina',
            name='bloques',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
