# Generated by Django 5.1.5 on 2025-01-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0004_alter_bloque_ejercicios_alter_bloque_rutina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='metodo_trabajo',
            field=models.CharField(choices=[('TIEMPO', 'Por tiempo'), ('REPETICION_DESCANSO', 'Por repetición con descanso'), ('CRECIENTE', 'En forma creciente'), ('OTRO', 'Otro')], default='TIEMPO', max_length=20),
        ),
        migrations.AddField(
            model_name='bloque',
            name='repeticiones_iniciales',
            field=models.PositiveIntegerField(blank=True, help_text='Repeticiones iniciales', null=True),
        ),
        migrations.AddField(
            model_name='bloque',
            name='tiempo_descanso',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de descanso en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Duración del bloque en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='ejercicios',
            field=models.ManyToManyField(related_name='bloques', to='ChillFit.ejercicio'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='rutina',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_de_rutina', to='ChillFit.rutina'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='bloques',
        ),
        migrations.AddField(
            model_name='rutina',
            name='bloques',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
