# Generated by Django 5.1.5 on 2025-01-15 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0005_bloque_metodo_trabajo_bloque_repeticiones_iniciales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='bloques',
        ),
        migrations.AlterField(
            model_name='bloque',
            name='metodo_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFit.metododetrabajo'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='bloques',
            field=models.ManyToManyField(related_name='rutinas', to='ChillFit.bloque'),
        ),
    ]
