# Generated by Django 5.1.5 on 2025-01-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0006_metododetrabajo_remove_bloque_rutina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='metodo_trabajo',
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='repeticiones_iniciales',
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='tiempo_descanso',
        ),
        migrations.RemoveField(
            model_name='metododetrabajo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='metododetrabajo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='bloque',
            name='metodo_de_trabajo',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='ChillFit.metododetrabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metododetrabajo',
            name='duracion',
            field=models.PositiveIntegerField(default=10, help_text='Duración en minutos (si es por tiempo)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metododetrabajo',
            name='repeticiones_iniciales',
            field=models.PositiveIntegerField(blank=True, help_text='Número inicial de repeticiones (si es por repetición)', null=True),
        ),
        migrations.AddField(
            model_name='metododetrabajo',
            name='tiempo_descanso',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de descanso entre repeticiones (si es por repetición)', null=True),
        ),
        migrations.AddField(
            model_name='metododetrabajo',
            name='tipo_de_trabajo',
            field=models.CharField(choices=[('TIEMPO', 'Por tiempo'), ('REPETICION', 'Por repetición con descanso'), ('CRECIENTE', 'Creciente (sumando repeticiones)')], default='TIEMPO', max_length=20),
        ),
    ]
