# Generated by Django 5.1.5 on 2025-01-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0007_remove_bloque_duracion_remove_bloque_metodo_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metododetrabajo',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='metododetrabajo',
            name='repeticiones_iniciales',
        ),
        migrations.RemoveField(
            model_name='metododetrabajo',
            name='tiempo_descanso',
        ),
        migrations.RemoveField(
            model_name='metododetrabajo',
            name='tipo_de_trabajo',
        ),
        migrations.AddField(
            model_name='metododetrabajo',
            name='descripcion',
            field=models.CharField(default=10, help_text='Descripción del método de trabajo', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='bloques',
        ),
        migrations.AddField(
            model_name='rutina',
            name='bloques',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
