# Generated by Django 5.1.5 on 2025-01-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0008_remove_metododetrabajo_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='ejercicios',
            field=models.ManyToManyField(to='ChillFit.ejercicio'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='metodo_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFit.metododetrabajo'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='bloques',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='duracion_total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='rutina',
            name='bloques',
            field=models.ManyToManyField(to='ChillFit.bloque'),
        ),
    ]
