# Generated by Django 5.1.5 on 2025-01-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0009_alter_bloque_ejercicios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='duracion_total',
        ),
        migrations.AlterField(
            model_name='metododetrabajo',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
