# Generated by Django 5.1.5 on 2025-01-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0010_remove_rutina_duracion_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='metododetrabajo',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
