# Generated by Django 5.1.5 on 2025-01-16 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0011_alter_ejercicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='ChillFit.usuario'),
        ),
    ]
