# Generated by Django 5.1.5 on 2025-01-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0013_alter_usuario_edad_alter_usuario_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
