# Generated by Django 5.1.5 on 2025-01-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0014_alter_usuario_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='ejercicios',
            field=models.ManyToManyField(blank=True, to='ChillFit.ejercicio'),
        ),
    ]
