# Generated by Django 5.1.5 on 2025-01-16 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0015_alter_bloque_ejercicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='plan_de_trabajo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='plandetrabajo',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='bloques',
            field=models.ManyToManyField(blank=True, to='ChillFit.bloque'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.PositiveIntegerField(default=18)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True)),
                ('plan_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ChillFit.plandetrabajo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
