# Generated by Django 5.1.5 on 2025-01-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0016_remove_usuario_edad_remove_usuario_plan_de_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='plan_de_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='ChillFit.plandetrabajo'),
        ),
        migrations.CreateModel(
            name='UsuarioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=False)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='ChillFit.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'rutina')},
            },
        ),
    ]
