# Generated by Django 5.1.5 on 2025-01-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0017_remove_rutina_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
