# Generated by Django 5.1.5 on 2025-01-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0018_bloque_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
