# Generated by Django 5.1.5 on 2025-03-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0021_remove_pago_pagado_pago_descripcion_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='id_pago_interno',
            field=models.CharField(default='PAY-00000', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='id_pago_mercadopago',
            field=models.CharField(blank=True, help_text='ID de MercadoPago', max_length=50, null=True),
        ),
    ]
