# Generated by Django 5.1.5 on 2025-03-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0022_pago_id_pago_interno_pago_id_pago_mercadopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_pago_interno',
        ),
        migrations.AddField(
            model_name='pago',
            name='id_pago_usuario',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
