# Generated by Django 5.1.5 on 2025-03-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0024_pago_plan_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_transferencia',
            field=models.FileField(blank=True, help_text='Solo para pagos informados por transferencia', null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('informado', 'Informado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
