# Generated by Django 5.1.5 on 2025-03-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0025_pago_comprobante_transferencia_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariorutina',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='usuariorutina',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
