# Generated by Django 5.1.5 on 2025-03-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0026_alter_usuariorutina_options_usuariorutina_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('mercadopago', 'MercadoPago'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
