# Generated by Django 5.1.5 on 2025-03-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0029_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFit.bloque')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillFit.ejercicio')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('bloque', 'ejercicio')},
            },
        ),
        migrations.AddField(
            model_name='bloque',
            name='ejercicios_ordenados',
            field=models.ManyToManyField(blank=True, related_name='bloques_ordenados', through='ChillFit.BloqueEjercicio', to='ChillFit.ejercicio'),
        ),
    ]
