# Generated by Django 5.1.5 on 2025-03-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0030_bloqueejercicio_bloque_ejercicios_ordenados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='ejercicios',
        ),
    ]
