# Generated by Django 5.1.5 on 2025-03-31 00:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0031_remove_bloque_ejercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante_transferencia',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Solo para pagos informados por transferencia', max_length=255, null=True, verbose_name='comprobante'),
        ),
    ]
