# Generated by Django 5.1.5 on 2025-04-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0032_alter_pago_comprobante_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='incluir_tabata',
            field=models.BooleanField(default=True, help_text='¿Mostrar temporizador Tabata en esta rutina?'),
        ),
    ]
