# Generated by Django 5.1.5 on 2025-05-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillFit', '0034_profesor_perfilusuario_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_profesor',
            field=models.BooleanField(default=False),
        ),
    ]
